### ISSUE TITLE
Editor crashes when saving

### ISSUE THREAD

**Issue by The4Pikmin** [ScottyThePilot/hoi4_province_editor#1]
I noticed this yesterday, and it seems to only happen in certain conditions.
Here is the error log:

```
The application panicked (crashed).
Message:  index out of bounds: the len is 8342 but the index is 8342
Location: src\app\map\bridge.rs:350

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: BaseThreadInitThunk
    at <unknown source file>
 2: RtlUserThreadStart
    at <unknown source file>
```

This seems to happen when I remove a province from the province map, and then hit save. This is crucial, I can't delete any provinces because of this bug! I'm not sure if this is a problem with my map or with the editor itself, but I can't understand what the editor is saying is wrong in this log.

**Comment by ScottyThePilot** [comment]
Hello, thank you for opening an issue! I believe I was able to reproduce the same out of bounds index crash that you experienced. I was able to reproduce it by painting over a single existing province and attempting to save the map with `preserve-ids` enabled. This bug should be fixed in the next release.
